affirmations = [
    {"id": 1, "string": "I accept myself completely and unconditionally.", "category": "Acceptance"},
    {"id": 2, "string": "I embrace all aspects of who I am.", "category": "Acceptance"},
    {"id": 3, "string": "I release the need for approval from others.", "category": "Acceptance"},
    {"id": 4, "string": "I am at peace with my past, present, and future.", "category": "Acceptance"},
    {"id": 5, "string": "I am enough just as I am.", "category": "Acceptance"},
    {"id": 6, "string": "I forgive myself for any mistakes I've made.", "category": "Acceptance"},
    {"id": 7, "string": "I let go of self-judgment and criticism.", "category": "Acceptance"},
    {"id": 8, "string": "I trust in my journey and embrace all experiences.", "category": "Acceptance"},
    {"id": 9, "string": "I am worthy of love and acceptance.", "category": "Acceptance"},
    {"id": 10, "string": "I honor and respect myself.", "category": "Acceptance"},
    {"id": 11, "string": "I am proud of who I am becoming.", "category": "Acceptance"},
    {"id": 12, "string": "I celebrate my uniqueness.", "category": "Acceptance"},
    {"id": 13, "string": "I am deserving of happiness and fulfillment.", "category": "Acceptance"},
    {"id": 14, "string": "I radiate confidence in who I am.", "category": "Acceptance"},
    {"id": 15, "string": "I am open to receiving love and kindness from myself and others.", "category": "Acceptance"},
    {"id": 16, "string": "I acknowledge my strengths and embrace my weaknesses.", "category": "Acceptance"},
    {"id": 17, "string": "I am worthy of love, respect, and compassion.", "category": "Acceptance"},
    {"id": 18, "string": "I release comparison and embrace my individuality.", "category": "Acceptance"},
    {"id": 19, "string": "I choose to see the beauty within myself.", "category": "Acceptance"},
    {"id": 20, "string": "I am worthy of all the good life has to offer.", "category": "Acceptance"},
    {"id": 21, "string": "I am whole and complete just as I am.", "category": "Acceptance"},
    {"id": 22, "string": "I am deserving of abundance and joy.", "category": "Acceptance"},
    {"id": 23, "string": "I trust in my abilities and inner wisdom.", "category": "Acceptance"},
    {"id": 24, "string": "I am free to be myself without fear of judgment.", "category": "Acceptance"},
    {"id": 25, "string": "I am on a journey of self-discovery and growth.", "category": "Acceptance"},
    {"id": 26, "string": "I am grateful for the gift of life.", "category": "Gratitude"},
    {"id": 27, "string": "I appreciate the abundance that surrounds me.", "category": "Gratitude"},
    {"id": 28, "string": "I am thankful for the love and support of my friends and family.", "category": "Gratitude"},
    {"id": 29, "string": "I express gratitude for the lessons I learn each day.", "category": "Gratitude"},
    {"id": 30, "string": "I am grateful for the beauty of nature.", "category": "Gratitude"},
    {"id": 31, "string": "I appreciate the little things that bring me joy.", "category": "Gratitude"},
    {"id": 32, "string": "I am thankful for the opportunities that come my way.", "category": "Gratitude"},
    {"id": 33, "string": "I am grateful for the love and kindness I receive from others.", "category": "Gratitude"},
    {"id": 34, "string": "I express gratitude for my health and well-being.", "category": "Gratitude"},
    {"id": 35, "string": "I am thankful for the freedom to choose my path.", "category": "Gratitude"},
    {"id": 36, "string": "I appreciate the abundance of love in my life.", "category": "Gratitude"},
    {"id": 37, "string": "I am grateful for the challenges that help me grow.", "category": "Gratitude"},
    {"id": 38, "string": "I express gratitude for the simple pleasures in life.", "category": "Gratitude"},
    {"id": 39, "string": "I am thankful for the opportunities to learn and grow.", "category": "Gratitude"},
    {"id": 40, "string": "I appreciate the support and guidance of my mentors.", "category": "Gratitude"},
    {"id": 41, "string": "I am grateful for the laughter and joy that fills my days.", "category": "Gratitude"},
    {"id": 42, "string": "I express gratitude for the abundance of love and joy in my life.", "category": "Gratitude"},
    {"id": 43, "string": "I am thankful for the beauty that surrounds me.", "category": "Gratitude"},
    {"id": 44, "string": "I appreciate the opportunities to connect with others.", "category": "Gratitude"},
    {"id": 45, "string": "I express gratitude for the abundance of blessings in my life.", "category": "Gratitude"},
    {"id": 46, "string": "I am grateful for the kindness of strangers.", "category": "Gratitude"},
    {"id": 47, "string": "I appreciate the love and support of my community.", "category": "Gratitude"},
    {"id": 48, "string": "I express gratitude for the experiences that shape me.", "category": "Gratitude"},
    {"id": 49, "string": "I am thankful for the strength and resilience within me.", "category": "Gratitude"},
    {"id": 50, "string": "I appreciate the gift of each new day.", "category": "Gratitude"},
    {"id": 51, "string": "I love and accept myself unconditionally.", "category": "Self-love"},
    {"id": 52, "string": "I deserve love and kindness.", "category": "Self-love"},
    {"id": 53, "string": "I am worthy of all the love in the world.", "category": "Self-love"},
    {"id": 54, "string": "I treat myself with compassion and understanding.", "category": "Self-love"},
    {"id": 55, "string": "I embrace my flaws and imperfections.", "category": "Self-love"},
    {"id": 56, "string": "I am proud of the person I am becoming.", "category": "Self-love"},
    {"id": 57, "string": "I am deserving of self-care and self-compassion.", "category": "Self-love"},
    {"id": 58, "string": "I forgive myself for any mistakes I've made.", "category": "Self-love"},
    {"id": 59, "string": "I trust in my ability to overcome challenges.", "category": "Self-love"},
    {"id": 60, "string": "I am worthy of my own love and affection.", "category": "Self-love"},
    {"id": 61, "string": "I honor my needs and prioritize self-care.", "category": "Self-love"},
    {"id": 62, "string": "I am deserving of happiness and fulfillment.", "category": "Self-love"},
    {"id": 63, "string": "I am worthy of all the good things life has to offer.", "category": "Self-love"},
    {"id": 64, "string": "I am confident in my own worth and value.", "category": "Self-love"},
    {"id": 65, "string": "I am proud of my accomplishments and achievements.", "category": "Self-love"},
    {"id": 66, "string": "I am deserving of love, respect, and kindness.", "category": "Self-love"},
    {"id": 67, "string": "I embrace my uniqueness and individuality.", "category": "Self-love"},
    {"id": 68, "string": "I trust in my intuition and inner wisdom.", "category": "Self-love"},
    {"id": 69, "string": "I am worthy of love and belonging.", "category": "Self-love"},
    {"id": 70, "string": "I am at peace with who I am.", "category": "Self-love"},
    {"id": 71, "string": "I am deserving of love and happiness.", "category": "Self-love"},
    {"id": 72, "string": "I love and accept myself exactly as I am.", "category": "Self-love"},
    {"id": 73, "string": "I am worthy of my own love and affection.", "category": "Self-love"},
    {"id": 74, "string": "I am enough just as I am.", "category": "Self-love"},
    {"id": 75, "string": "I am deserving of love and affection.", "category": "Love"},
    {"id": 76, "string": "I attract loving and supportive relationships into my life.", "category": "Love"},
    {"id": 77, "string": "I give and receive love freely.", "category": "Love"},
    {"id": 78, "string": "I am open to giving and receiving love.", "category": "Love"},
    {"id": 79, "string": "I am surrounded by love in all forms.", "category": "Love"},
    {"id": 80, "string": "I am worthy of a deep and fulfilling love.", "category": "Love"},
    {"id": 81, "string": "I deserve to be cherished and adored.", "category": "Love"},
    {"id": 82, "string": "I am open to finding love in unexpected ways.", "category": "Love"},
    {"id": 83, "string": "I am deserving of a healthy and loving relationship.", "category": "Love"},
    {"id": 84, "string": "I am lovable and worthy of love.", "category": "Love"},
    {"id": 85, "string": "I am worthy of being loved for who I truly am.", "category": "Love"},
    {"id": 86, "string": "I am open to experiencing love in all its forms.", "category": "Love"},
    {"id": 87, "string": "I am grateful for the love that fills my heart.", "category": "Love"},
    {"id": 88, "string": "I attract loving and caring people into my life.", "category": "Love"},
    {"id": 89, "string": "I am worthy of love and affection.", "category": "Love"},
    {"id": 90, "string": "I am surrounded by love and support.", "category": "Love"},
    {"id": 91, "string": "I am deserving of a passionate and fulfilling relationship.", "category": "Love"},
    {"id": 92, "string": "I radiate love and compassion.", "category": "Love"},
    {"id": 93, "string": "I am open to giving and receiving love without fear.", "category": "Love"},
    {"id": 94, "string": "I am deserving of a deep and meaningful connection.", "category": "Love"},
    {"id": 95, "string": "I am worthy of a love that is unconditional and true.", "category": "Love"},
    {"id": 96, "string": "I attract love and positivity into my life.", "category": "Love"},
    {"id": 97, "string": "I am deserving of love and happiness.", "category": "Love"},
    {"id": 98, "string": "I am open to receiving love from myself and others.", "category": "Love"},
    {"id": 99, "string": "I am worthy of a love that lifts me up and inspires me.", "category": "Love"},
    {"id": 100, "string": "I am surrounded by supportive and loyal friends.", "category": "Friendship"},
    {"id": 101, "string": "I attract positive and uplifting friendships into my life.", "category": "Friendship"},
    {"id": 102, "string": "I am a good friend who is there for others.", "category": "Friendship"},
    {"id": 103, "string": "I am deserving of true and authentic friendships.", "category": "Friendship"},
    {"id": 104, "string": "I am grateful for the friends who bring joy into my life.", "category": "Friendship"},
    {"id": 105, "string": "I attract friends who share similar values and interests.", "category": "Friendship"},
    {"id": 106, "string": "I am open to forming new and meaningful friendships.", "category": "Friendship"},
    {"id": 107, "string": "I am a loyal and dependable friend.", "category": "Friendship"},
    {"id": 108, "string": "I am surrounded by friends who accept me for who I am.", "category": "Friendship"},
    {"id": 109, "string": "I am deserving of friends who support and encourage me.", "category": "Friendship"},
    {"id": 110, "string": "I am grateful for the laughter and fun my friends bring.", "category": "Friendship"},
    {"id": 111, "string": "I attract friends who inspire me to be the best version of myself.", "category": "Friendship"},
    {"id": 112, "string": "I am open to deepening existing friendships.", "category": "Friendship"},
    {"id": 113, "string": "I am surrounded by friends who lift me up when I'm down.", "category": "Friendship"},
    {"id": 114, "string": "I am grateful for the memories shared with my friends.", "category": "Friendship"},
    {"id": 115, "string": "I attract friends who share my values and aspirations.", "category": "Friendship"},
    {"id": 116, "string": "I am deserving of friends who celebrate my successes.", "category": "Friendship"},
    {"id": 117, "string": "I am open to nurturing and strengthening my friendships.", "category": "Friendship"},
    {"id": 118, "string": "I am surrounded by friends who make me feel understood and valued.", "category": "Friendship"},
    {"id": 119, "string": "I am grateful for the support and encouragement of my friends.", "category": "Friendship"},
    {"id": 120, "string": "I attract friends who accept me unconditionally.", "category": "Friendship"},
    {"id": 121, "string": "I am deserving of friendships that bring out the best in me.", "category": "Friendship"},
    {"id": 122, "string": "I am open to connecting with like-minded individuals.", "category": "Friendship"},
    {"id": 123, "string": "I am surrounded by friends who inspire and uplift me.", "category": "Friendship"},
    {"id": 124, "string": "I am grateful for the laughter and", "category": "Friendship"},
    {"id": 125, "string": "I am surrounded by supportive and loving family members.", "category": "Family"},
    {"id": 126, "string": "I am grateful for the bond I share with my family.", "category": "Family"},
    {"id": 127, "string": "I am connected to my family with love and understanding.", "category": "Family"},
    {"id": 128, "string": "I am surrounded by family members who support and uplift me.", "category": "Family"},
    {"id": 129, "string": "I cherish the memories I create with my family.", "category": "Family"},
    {"id": 130, "string": "I am grateful for the traditions and values passed down by my family.", "category": "Family"},
    {"id": 131, "string": "I am a source of love and support for my family.", "category": "Family"},
    {"id": 132, "string": "I am open to resolving conflicts and strengthening bonds within my family.", "category": "Family"},
    {"id": 133, "string": "I am deserving of a happy and harmonious family life.", "category": "Family"},
    {"id": 134, "string": "I am surrounded by love and understanding within my family.", "category": "Family"},
    {"id": 135, "string": "I am grateful for the lessons I learn from my family.", "category": "Family"},
    {"id": 136, "string": "I am a source of strength and support for my family members.", "category": "Family"},
    {"id": 137, "string": "I am open to creating new traditions and memories with my family.", "category": "Family"},
    {"id": 138, "string": "I am surrounded by family members who inspire and motivate me.", "category": "Family"},
    {"id": 139, "string": "I am grateful for the love and guidance of my family.", "category": "Family"},
    {"id": 140, "string": "I am connected to my family through love and understanding.", "category": "Family"},
    {"id": 141, "string": "I am deserving of a close and loving relationship with my family.", "category": "Family"},
    {"id": 142, "string": "I am surrounded by family members who accept me for who I am.", "category": "Family"},
    {"id": 143, "string": "I am open to deepening the bonds of love and connection within my family.", "category": "Family"},
    {"id": 144, "string": "I am grateful for the laughter and joy shared with my family.", "category": "Family"},
    {"id": 145, "string": "I am surrounded by loving and supportive colleagues.", "category": "Work"},
    {"id": 146, "string": "I am appreciated and valued for my contributions at work.", "category": "Work"},
    {"id": 147, "string": "I am successful in my career and continue to grow professionally.", "category": "Work"},
    {"id": 148, "string": "I am open to new opportunities and challenges in my work.", "category": "Work"},
    {"id": 149, "string": "I am confident in my abilities to achieve success in my career.", "category": "Work"},
    {"id": 150, "string": "I am respected and admired by my peers and superiors.", "category": "Work"},
    {"id": 151, "string": "I am capable of overcoming any obstacles that arise in my work.", "category": "Work"},
    {"id": 152, "string": "I am motivated and focused on achieving my career goals.", "category": "Work"},
    {"id": 153, "string": "I am grateful for the opportunities to learn and grow in my profession.", "category": "Work"},
    {"id": 154, "string": "I am surrounded by a positive and supportive work environment.", "category": "Work"},
    {"id": 155, "string": "I am deserving of success and recognition in my career.", "category": "Work"},
    {"id": 156, "string": "I am confident in my ability to overcome challenges and achieve my goals.", "category": "Work"},
    {"id": 157, "string": "I am grateful for the fulfillment and satisfaction my work brings.", "category": "Work"},
    {"id": 158, "string": "I am open to new opportunities for growth and advancement in my career.", "category": "Work"},
    {"id": 159, "string": "I am surrounded by supportive mentors and colleagues who inspire me.", "category": "Work"},
    {"id": 160, "string": "I am committed to achieving excellence in my work.", "category": "Work"},
    {"id": 161, "string": "I am proud of my accomplishments and contributions in my career.", "category": "Work"},
    {"id": 162, "string": "I am deserving of success and recognition for my hard work.", "category": "Work"},
    {"id": 163, "string": "I am motivated to make a positive impact through my work.", "category": "Work"},
    {"id": 164, "string": "I am grateful for the opportunities to collaborate and learn from others at work.", "category": "Work"},
    {"id": 165, "string": "I am surrounded by supportive friends and mentors who help me grow in my career.", "category": "Work"},
    {"id": 166, "string": "I am committed to continuous learning and improvement in my profession.", "category": "Work"},
    {"id": 167, "string": "I am confident in my ability to overcome challenges and achieve success in my work.", "category": "Work"},
    {"id": 168, "string": "I am motivated to pursue my passions and interests in my career.", "category": "Work"},
    {"id": 169, "string": "I am grateful for the opportunities to contribute my unique skills and talents at work.", "category": "Work"},
    {"id": 170, "string": "I am surrounded by a supportive network of colleagues and mentors who encourage my growth.", "category": "Work"},
    {"id": 171, "string": "I am committed to achieving my academic goals.", "category": "School"},
    {"id": 172, "string": "I am capable of learning and mastering new concepts.", "category": "School"},
    {"id": 173, "string": "I am confident in my ability to succeed academically.", "category": "School"},
    {"id": 174, "string": "I am focused and motivated to excel in my studies.", "category": "School"},
    {"id": 175, "string": "I am open to new opportunities for learning and growth.", "category": "School"},
    {"id": 176, "string": "I am dedicated to putting in the effort needed to achieve my academic goals.", "category": "School"},
    {"id": 177, "string": "I am deserving of success and recognition in my academic pursuits.", "category": "School"},
    {"id": 178, "string": "I am committed to expanding my knowledge and understanding.", "category": "School"},
    {"id": 179, "string": "I am capable of overcoming any challenges that arise in my studies.", "category": "School"},
    {"id": 180, "string": "I am grateful for the opportunities to learn and grow in my education.", "category": "School"},
    {"id": 181, "string": "I am confident in my ability to achieve my academic goals.", "category": "School"},
    {"id": 182, "string": "I am motivated to make the most of my educational experiences.", "category": "School"},
    {"id": 183, "string": "I am open to exploring new ideas and perspectives in my studies.", "category": "School"},
    {"id": 184, "string": "I am committed to putting forth my best effort in my academic endeavors.", "category": "School"},
    {"id": 185, "string": "I am focused and determined to succeed in my education.", "category": "School"},
    {"id": 186, "string": "I am capable of achieving excellence in my academic pursuits.", "category": "School"},
    {"id": 187, "string": "I am deserving of recognition for my hard work and dedication in school.", "category": "School"},
    {"id": 188, "string": "I am grateful for the support and encouragement of my teachers and peers.", "category": "School"},
    {"id": 189, "string": "I am confident in my ability to learn and grow through my educational experiences.", "category": "School"},
    {"id": 190, "string": "I am motivated to pursue my academic passions and interests.", "category": "School"},
    {"id": 191, "string": "I am open to new opportunities for personal and intellectual growth.", "category": "School"},
    {"id": 192, "string": "I am committed to making the most of my educational opportunities.", "category": "School"},
    {"id": 193, "string": "I am focused and determined to succeed in my studies.", "category": "School"},
    {"id": 194, "string": "I am capable of achieving my academic goals.", "category": "School"},
    {"id": 195, "string": "I am deserving of success and recognition in my academic pursuits.", "category": "School"},
    {"id": 196, "string": "I am confident in my ability to overcome challenges and achieve my goals.", "category": "School"},
    {"id": 197, "string": "I am motivated to pursue my passions and interests in my education.", "category": "School"},
    {"id": 198, "string": "I am grateful for the opportunities to expand my knowledge and understanding.", "category": "School"},
    {"id": 199, "string": "I am surrounded by a supportive community that values education and learning.", "category": "School"},
    {"id": 200, "string": "I am committed to achieving success in my academic pursuits.", "category": "School"},
    {"id": 201, "string": "I honor my body and treat it with kindness.", "category": "Health"},
    {"id": 202, "string": "I am committed to living a healthy and balanced life.", "category": "Health"},
    {"id": 203, "string": "I attract positive energy and vitality into my life.", "category": "Health"},
    {"id": 204, "string": "I am grateful for the strength and resilience within me.", "category": "Health"},
    {"id": 205, "string": "I listen to my body's needs and prioritize self-care.", "category": "Health"},
    {"id": 206, "string": "I am worthy of good health and well-being.", "category": "Health"},
    {"id": 207, "string": "I nourish my body with healthy foods and exercise.", "category": "Health"},
    {"id": 208, "string": "I am deserving of a healthy and vibrant life.", "category": "Health"},
    {"id": 209, "string": "I am open to healing and renewal in mind, body, and spirit.", "category": "Health"},
    {"id": 210, "string": "I trust in my body's ability to heal and regenerate.", "category": "Health"},
    {"id": 211, "string": "I am grateful for the opportunity to care for my body.", "category": "Health"},
    {"id": 212, "string": "I honor my body's need for rest and relaxation.", "category": "Health"},
    {"id": 213, "string": "I am committed to creating a life filled with health and vitality.", "category": "Health"},
    {"id": 214, "string": "I am surrounded by positive influences that support my health goals.", "category": "Health"},
    {"id": 215, "string": "I am grateful for the energy and vitality that flows through me.", "category": "Health"},
    {"id": 216, "string": "I trust in my body's ability to heal and restore itself.", "category": "Health"},
    {"id": 217, "string": "I am open to new ways of nurturing my body, mind, and spirit.", "category": "Health"},
    {"id": 218, "string": "I am deserving of a life filled with health, happiness, and abundance.", "category": "Health"},
    {"id": 219, "string": "I honor my body as a sacred vessel of life.", "category": "Health"},
    {"id": 220, "string": "I am grateful for the wisdom and intuition of my body.", "category": "Health"},
    {"id": 221, "string": "I am committed to making choices that support my health and well-being.", "category": "Health"},
    {"id": 222, "string": "I am surrounded by love and support as I pursue my health goals.", "category": "Health"},
    {"id": 223, "string": "I am open to receiving guidance and healing from within.", "category": "Health"},
    {"id": 224, "string": "I trust in the natural rhythms of my body and honor its needs.", "category": "Health"},
    {"id": 225, "string": "I am worthy of vibrant health and well-being.", "category": "Health"},
    {"id": 226, "string": "I am open to receiving abundance in all areas of my life.", "category": "Wealth"},
    {"id": 227, "string": "I attract prosperity and abundance with ease.", "category": "Wealth"},
    {"id": 228, "string": "I am deserving of wealth and success.", "category": "Wealth"},
    {"id": 229, "string": "I am grateful for the abundance that flows into my life.", "category": "Wealth"},
    {"id": 230, "string": "I am open to receiving money and opportunities from unexpected sources.", "category": "Wealth"},
    {"id": 231, "string": "I am worthy of financial security and stability.", "category": "Wealth"},
    {"id": 232, "string": "I release all limiting beliefs about money and embrace abundance.", "category": "Wealth"},
    {"id": 233, "string": "I am a magnet for wealth and prosperity.", "category": "Wealth"},
    {"id": 234, "string": "I am open to receiving unlimited abundance in my life.", "category": "Wealth"},
    {"id": 235, "string": "I am grateful for the wealth and abundance that surrounds me.", "category": "Wealth"},
    {"id": 236, "string": "I attract opportunities for wealth and success.", "category": "Wealth"},
    {"id": 237, "string": "I am deserving of abundance in all areas of my life.", "category": "Wealth"},
    {"id": 238, "string": "I am open to receiving wealth and prosperity with gratitude.", "category": "Wealth"},
    {"id": 239, "string": "I am worthy of living a life of abundance and fulfillment.", "category": "Wealth"},
    {"id": 240, "string": "I release all fears and doubts about my ability to attract wealth.", "category": "Wealth"},
    {"id": 241, "string": "I am grateful for the opportunities to create wealth and abundance.", "category": "Wealth"},
    {"id": 242, "string": "I am open to receiving prosperity from all directions.", "category": "Wealth"},
    {"id": 243, "string": "I am deserving of financial freedom and independence.", "category": "Wealth"},
    {"id": 244, "string": "I am worthy of receiving abundance in all areas of my life.", "category": "Wealth"},
    {"id": 245, "string": "I am open to receiving wealth in miraculous ways.", "category": "Wealth"},
    {"id": 246, "string": "I am grateful for the abundance that flows into my life effortlessly.", "category": "Wealth"},
    {"id": 247, "string": "I attract happiness and joy into my life.", "category": "Happiness"},
    {"id": 248, "string": "I am deserving of happiness and fulfillment.", "category": "Happiness"},
    {"id": 249, "string": "I choose happiness in every moment.", "category": "Happiness"},
    {"id": 250, "string": "I am grateful for the joy that fills my heart.", "category": "Happiness"},
    {"id": 251, "string": "I find joy in the simple pleasures of life.", "category": "Happiness"},
    {"id": 252, "string": "I am open to experiencing happiness in all areas of my life.", "category": "Happiness"},
    {"id": 253, "string": "I release all fears and doubts that prevent me from experiencing happiness.", "category": "Happiness"},
    {"id": 254, "string": "I am worthy of a life filled with happiness and abundance.", "category": "Happiness"},
    {"id": 255, "string": "I am grateful for the love and happiness that surrounds me.", "category": "Happiness"},
    {"id": 256, "string": "I am deserving of love, joy, and success.", "category": "Happiness"},
    {"id": 257, "string": "I choose to focus on the positive and find happiness in every situation.", "category": "Happiness"},
    {"id": 258, "string": "I am open to receiving happiness from unexpected sources.", "category": "Happiness"},
    {"id": 259, "string": "I am worthy of happiness and fulfillment.", "category": "Happiness"},
    {"id": 260, "string": "I release all worries and embrace the happiness that is within me.", "category": "Happiness"},
    {"id": 261, "string": "I am grateful for the abundance of happiness in my life.", "category": "Happiness"},
    {"id": 262, "string": "I attract positive experiences and joyful moments.", "category": "Happiness"},
    {"id": 263, "string": "I am deserving of a life filled with happiness and peace.", "category": "Happiness"},
    {"id": 264, "string": "I choose to be happy and content with what I have.", "category": "Happiness"},
    {"id": 265, "string": "I am open to receiving happiness and joy in all areas of my life.", "category": "Happiness"},
    {"id": 266, "string": "I am grateful for the happiness that flows through me.", "category": "Happiness"},
    {"id": 267, "string": "I attract success and abundance into my life.", "category": "Success"},
    {"id": 268, "string": "I am capable of achieving greatness.", "category": "Success"},
    {"id": 269, "string": "I am deserving of success and prosperity.", "category": "Success"},
    {"id": 270, "string": "I am confident in my ability to succeed.", "category": "Success"},
    {"id": 271, "string": "I am committed to achieving my goals.", "category": "Success"},
    {"id": 272, "string": "I am focused and determined to succeed.", "category": "Success"},
    {"id": 273, "string": "I am open to receiving opportunities for success.", "category": "Success"},
    {"id": 274, "string": "I am worthy of success and recognition.", "category": "Success"},
    {"id": 275, "string": "I am grateful for the abundance of success in my life.", "category": "Success"},
    {"id": 276, "string": "I attract opportunities for growth and advancement.", "category": "Success"},
    {"id": 277, "string": "I am deserving of recognition for my accomplishments.", "category": "Success"},
    {"id": 278, "string": "I am capable of overcoming any obstacles on my path to success.", "category": "Success"},
    {"id": 279, "string": "I am committed to becoming the best version of myself.", "category": "Success"},
    {"id": 280, "string": "I am open to receiving the rewards of my hard work and dedication.", "category": "Success"},
    {"id": 281, "string": "I am confident in my ability to achieve my dreams.", "category": "Success"},
    {"id": 282, "string": "I am worthy of success and abundance in all areas of my life.", "category": "Success"},
    {"id": 283, "string": "I am grateful for the opportunities to grow and succeed.", "category": "Success"},
    {"id": 284, "string": "I attract success and prosperity with every decision I make.", "category": "Success"},
    {"id": 285, "string": "I am deserving of all the good things life has to offer.", "category": "Success"}
]